[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
adra-lrt = "Lrt1aE9sgjyi6B9QEdcuzHC8GhU32N3PM9RSKLBeD7b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/adra-lrt"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
